### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by ujihisa** [osyo-manga/vim-jplus#1]
doc/jplus.jaxはあるもののdoc/jplus.txtがありません

> 行を結合する際に挿入する文字を入力して行の結合を行う。

    |jplus.vim| concatenates lines by asking which character to insert between them when it concatenates lines.

> 任意のキーにマッピングして使用します。

    Map them to keys that you prefer.

**Comment by osyo-manga** [comment]
追加されたので閉じます。
