### ISSUE TITLE
結合文字に&を使用した時、&でなく%dで結合される

### ISSUE THREAD

**Issue by u10e10** [osyo-manga/vim-jplus#12]
結合文字に&を使用した場合に&が挿入されず、代わりに%dが挿入されてしまいます。
ざっと見たところsubstitute()でのデリミタのエスケープ漏れに思えます。

**Comment by osyo-manga** [comment]
ありがとうございます。
修正したので確認をお願いします。

**Comment by u10e10** [comment]
確認しました。
対応ありがとうございます。

**Comment by osyo-manga** [comment]
ありがとうございました :)
