### ISSUE TITLE
formatoptions+=j でコメントリーダーが削除されない

### ISSUE THREAD

**Issue by NigoroJr** [osyo-manga/vim-jplus#6]
`set formatoptions+=j`でコメント行を結合したときにコメントリーダーが削除されるようにした場合でも、jplus.vimを有効にしているとリーダーが削除されません。`s:join(config)`を見た感じjplus.vim側で結合したものを現在の行と置換している？みたいなので、仕方ないのでしょうか？

**Comment by osyo-manga** [comment]
ありがとうございます。
問題点は把握しました。
確かに jplus.vim では

**Comment by NigoroJr** [comment]
ありがとうございます。私も似たようなことを考えてみたのですが、一つ一つ`filetype`を設定せずに済む方法があったり？と思いお聞きしてみました。
私の方でも弄ってみて、もし運良くうまくいったらPR送らせてもらうことにします。
お忙しいとのことですが、現在設定している`nmap <Leader>J <Plug>(jplus)`でも十分に便利ですので @osyo-manga さんにお時間ができたときに見て頂くので全く問題ありません。
今のところはこのIssueは開いたままにしておきます。ありがとうございました。

**Comment by osyo-manga** [comment]
> 一つ一つfiletypeを設定せずに済む方法があったり？と思いお聞きしてみました。

`filetype` ごとにコメントリーダーは異なるので現状だとどうしようもないですねぇ。
これを実装するためにはまず『各言語のコメントリーダーのDB』みたいなのが必要になると思います。

**Comment by NigoroJr** [comment]
Mergeして頂いたのでこちらも閉じさせてもらいます。
ありがとうございました。

**Comment by osyo-manga** [comment]
ありがとうございましたっ
